Revert "Switch module field path in package.json"
This reverts commit ebd714b5b7363d56f934fd020f29f0856e1ea733.

That commit causes the following error, presumably because Leaflet does not use
ES6 modules yet (see https://github.com/Leaflet/Leaflet/issues/7055).

  Uncaught TypeError: leaflet__WEBPACK_IMPORTED_MODULE_5___default.a.control.heightgraph is not a function